### ISSUE TITLE
plugin status ?

### ISSUE THREAD

**Issue by rienafairefr** [pelican-plugins/pdf#4]
I'd used a `pdf` pelican-plugin in the past to export articles to pdf, that was last year, I can't remember & can't recover which versions of python/pelican/pdf plugin I used then. I'm trying to modify->re-build/re-generate  and with these versions: Python 3.8/Pelican 4.2.0/pelican pdf master 8596c54a6e4d5/xhtml2pdf 0.2.5, I can't, getting this error:
```
CRITICAL: partially initialized module 'xhtml2pdf.util' has no attribute 'get_default_asian_font' (most likely due to a circular import)
```
With a cursory search, I couldn't find version combinations that would work. Any known incompatibilities in using that plugin ?

**Comment by justinmayer** [comment]
Hi Matthieu. I can't tell from your issue description exactly what versions of Pelican and its PDF plugin you tried, but I'm not aware of any problems with the current versions: Pelican 4.6 and PDF Generator 1.0

What happens when you create a fresh virtual environment and follow the instructions in this repository's README to install this plugin and generate PDFs?

**Comment by rienafairefr** [comment]
Thanks for looking into this,
I've tried with both pelican 4.6.0 or 4.2.0 in a fresh venv, the `pelican-plugins` folder cloned from https://github.com/getpelican/pelican-plugins, PLUGIN_PATHS pointing to it, not sure about the pdf generator version on there. pelican-pdf on pypi wasn't there when I tried (it's apparently released now ? https://pypi.org/project/pelican-pdf/), so I'll try that. This is a full debug/stacktrace:

```
$ inv build
pelican content -s pelicanconf.py -o output -D
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.8.5
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `i18n_subsites`
DEBUG: Registering plugin `i18n_subsites`
DEBUG: Loading plugin `pdf`
CRITICAL: AttributeError: partially initialized module 'xhtml2pdf.util' has no attribute 'get_default_asian_font' (most likely due to a circular import)
Traceback (most recent call last):
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/lib/python3.8/site-packages/pelican/__init__.py", line 512, in main
    pelican, settings = get_instance(args)
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/lib/python3.8/site-packages/pelican/__init__.py", line 405, in get_instance
    return cls(settings), settings
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/lib/python3.8/site-packages/pelican/__init__.py", line 63, in __init__
    self.init_plugins()
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/lib/python3.8/site-packages/pelican/__init__.py", line 82, in init_plugins
    plugin = __import__(plugin, globals(), locals(),
  File "/home/matthieu/pelican-plugins/pdf/__init__.py", line 1, in <module>
    from .pdf import *
  File "/home/matthieu/pelican-plugins/pdf/pdf.py", line 21, in <module>
    import xhtml2pdf.util
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/lib/python3.8/site-packages/xhtml2pdf/util.py", line 12, in <module>
    import xhtml2pdf.default
  File "/home/matthieu/.virtualenvs/resume-rienafairefr-github-io/lib/python3.8/site-packages/xhtml2pdf/default.py", line 611, in <module>
    DEFAULT_ASIAN_FONT = util.get_default_asian_font()
AttributeError: partially initialized module 'xhtml2pdf.util' has no attribute 'get_default_asian_font' (most likely due to a circular import)
 ```

**Comment by justinmayer** [comment]
That’s why I said to follow the README instructions from *this* repository. The old PDF plugin from the monolithic repository is now irrelevant and unsupported.

**Comment by wombelix** [comment]
The Plugin is working with the latest Pelican Version when installed via pip, also due to missing Feedback I think this Issue can be closed and is not relevant anymore.
